name: build binaries
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install requirements
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine32 wine64 build-essential git clang libasound2-dev \
            libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev \
            libxcursor-dev libxinerama-dev xxd libglfw3-dev wget sbcl unzip \
            winetricks pandoc \
            texlive-base texlive-binaries texlive-fonts-recommended \
            texlive-latex-base texlive-latex-extra texlive-latex-recommended \
            texlive-luatex texlive-pictures texlive-plain-generic \
            texlive-xetex
      - name: download fonts
        run: |
          sudo mkdir -p /usr/share/fonts
          sudo wget https://pub.krzysckh.org/_fonts/lg/LucidaGrande-Regular.otf -O /usr/share/fonts/LucidaGrande-Regular.otf
          sudo wget https://pub.krzysckh.org/_fonts/lg/LucidaGrande-Bold.otf -O /usr/share/fonts/LucidaGrande-Bold.otf
          sudo wget https://pub.krzysckh.org/_fonts/lg/LucidaGrande-Italic.otf -O /usr/share/fonts/LucidaGrande-Italic.otf
          sudo wget https://pub.krzysckh.org/_fonts/lg/LucidaGrande-BoldItalic.otf -O /usr/share/fonts/LucidaGrande-BoldItalic.otf
          sudo wget https://pub.krzysckh.org/_fonts/Apl385.ttf -O /usr/share/fonts/Apl385.ttf
          fc-cache -fv
      - name: install quicklisp
        run: |
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --quit
      - name: install sbcl for windows & build & test
        run: |
          Xvfb :1 &
          wget https://pub.krzysckh.org/msc25/sbcl.exe
          wget https://pub.krzysckh.org/msc25/sbcl.core
          wget https://pub.krzysckh.org/msc25/contrib.tgz
          wget https://pub.krzysckh.org/msc25/raylib5.5.dll
          wget https://pub.krzysckh.org/msc25/raylib5.5.so
          wget https://pub.krzysckh.org/msc25/libffi-8.dll
          file sbcl.exe
          tar xvzf contrib.tgz
          wget -nc https://beta.quicklisp.org/quicklisp.lisp
          # claim ownership
          mkdir /tmp/x
          export DISPLAY=:1
          export WINEPREFIX=/tmp/x/w
          export WINEARCH=win64
          wine sbcl.exe --core sbcl.core --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql:add-to-init-file)' --quit
          pushd .
          cd $WINEPREFIX
          wget https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_5380_5361/strawberry-perl-5.38.0.1-64bit-portable.zip
          unzip strawberry-perl-5.38.0.1-64bit-portable.zip
          popd
          CC="$WINEPREFIX/c/bin/gcc.exe" CFLAGS="-I." LDFLAGS="-L." make all

          cp -v libffi-8.dll build/
          cp -v raylib5.5.dll build/

          make test SBCL="wine sbcl.exe --core sbcl.core"
      - name: build docs
        run: |
          make docs
          cp -v doc/*.pdf build/
      - name: upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
