name: build binaries
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install requirements
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine32 wine64 build-essential git clang libasound2-dev \
            libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev \
            libxcursor-dev libxinerama-dev xxd libglfw3-dev wget sbcl unzip \
            winetricks
      - name: install quicklisp
        run: |
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --quit
      - name: install buildapp
        run: |
          cd /tmp
          wget http://www.xach.com/lisp/buildapp.tgz
          tar xvzf buildapp.tgz
          cd buildapp*/
          sudo make install
      - name: install sbcl for windows & build
        run: |
          Xvfb :1 &
          wget https://pub.krzysckh.org/msc25/sbcl.exe
          wget https://pub.krzysckh.org/msc25/sbcl.core
          wget https://pub.krzysckh.org/msc25/contrib.tgz
          wget https://pub.krzysckh.org/msc25/raylib5.5.dll
          wget https://pub.krzysckh.org/msc25/raylib5.5.so
          wget https://pub.krzysckh.org/msc25/libffi-8.dll
          file sbcl.exe
          tar xvzf contrib.tgz
          wget https://beta.quicklisp.org/quicklisp.lisp
          # claim ownership
          mkdir /tmp/x
          export DISPLAY=:1
          export WINEPREFIX=/tmp/x/w
          export WINEARCH=win32
          winetricks arch=32 -q mingw
          wine64 sbcl.exe --core sbcl.core --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql:add-to-init-file)' --quit
          WINE=wine64 CFLAGS="-I." LDFLAGS="-L." make

          cp libffi-8.dll build/
          cp raylib5.5.dll build/
      - name: upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
