name: build binaries
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install requirements
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y xvfb build-essential sbcl wine wine32:i386 wget libturbojpeg0-dev tk tklib tcllib libtk-img libsdl2-dev libgl-dev libsdl2-ttf-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev
      - name: install quicklisp
        run: |
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --quit
      - name: install buildapp
        run: |
          cd /tmp
          wget http://www.xach.com/lisp/buildapp.tgz
          tar xvzf buildapp.tgz
          cd buildapp*/
          sudo make install
      - name: install sbcl for windows & build
        run: |
          Xvfb :1 &
          pushd .
          cd /tmp
          wget https://pub.krzysckh.org/msc25/sbcl-installer.msi
          DISPLAY=:1 wine msiexec /i sbcl-installer.msi /qn || true
          popd
          DISPLAY=:1 make
      - name: upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
